FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

COPY ./FasteignirApi ./FasteignirApi
COPY ./FasteignirCommon ./FasteignirCommon

RUN dotnet restore FasteignirApi/FasteignirApi.csproj
RUN dotnet publish FasteignirApi/FasteignirApi.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "FasteignirApi.dll"]