# Use an official Node.js runtime as the base image
FROM node:14 AS build


WORKDIR /app

COPY ./fasteignarweb/package*.json ./
RUN npm install

COPY ./fasteignarweb .

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]